##################################
# 기본 네트워크
##################################
bind 0.0.0.0
port 6379
protected-mode no

##################################
# 메모리 정책 (재고 기준)
##################################
maxmemory 0
maxmemory-policy noeviction

##################################
# Persistence (재고 핵심)
##################################

# RDB (보조 스냅샷)
save 900 1
save 300 10
save 60 10000

# AOF (필수)
appendonly yes
appendfilename "appendonly.aof"

# fsync 정책
appendfsync everysec
no-appendfsync-on-rewrite yes

# AOF rewrite
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

##################################
# 성능 / 안정성
##################################
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes

##################################
# 로그
##################################
loglevel notice
logfile ""

##################################
# Keyspace (선택)
##################################
notify-keyspace-events ""
